---
# one day add postgresql here too, depending on a variable
#
#
- name: ensure mysql is running
  service: name=mysql state=started enabled=yes

- name: Disable Redis listening on TCP by setting 'port' to 0
  copy:
    src: 'redis.conf'
    dest: '/etc/redis/redis.conf'
    owner: 'root'
    group: 'root'
    mode: '644'
  notify:
    - restart redis

- name: ensure database for gitlab exists
  mysql_db: state=present name={{ gitlab_db_name }} collation=utf8_unicode_ci encoding=utf8

- name: ensure database user for gitlab is present and has privleges
  mysql_user: state=present host=localhost name={{ gitlab_db_user }} password={{ gitlab_db_passwd }} priv={{ gitlab_db_name }}.*:ALL
