---
- hosts: docker
  roles:
    - role: yabusygin.gitlab
  vars:
    docker_userns_remap_enable: yes

    gitlab_docker_image: gitlab/gitlab-ce:12.7.6-ce.0
    gitlab_docker_hostname: gitlab
    gitlab_docker_restart_policy: always

    gitlab_external_url: http://10.42.0.104:8000
    gitlab_nginix_listen_port: 80
    gitlab_rails_gitlab_shell_ssh_port: 2222

    gitlab_rails_monitoring_whitelist:
      - 127.0.0.0/8
      - 10.42.0.0/24

    gitlab_rails_smtp_enable: "true"
    gitlab_rails_smtp_address: smtp.example.com
    gitlab_rails_smtp_port: 465
    gitlab_rails_smtp_user_name: gitlab
    gitlab_rails_smtp_password: 'Pa$$w0rD'
    gitlab_rails_smtp_domain: example.com
    gitlab_rails_smtp_authentication: login
    gitlab_rails_smtp_tls: "true"
    gitlab_rails_smtp_enable_starttls_auto: "true"
    gitlab_rails_smtp_openssl_verify_mode: peer

    gitlab_rails_gitlab_email_enabled: "true"
    gitlab_rails_gitlab_email_from: gitlab@example.com
    gitlab_rails_gitlab_email_display_name: GitLab
    gitlab_rails_gitlab_email_reply_to: noreply@example.com

    gitlab_unicorn_worker_processes: 3
