# file: roles/python/tasks/main.yml

- name: Python | Make sure python packages are installed
  apt: pkg={{ item }}
  with_items:
    - cython
    - libevent-dev
    - python
    - python3
    - python-dev
    - python-pip


- name: Python | upgrade of pip
  shell: pip install --upgrade pip 

- name: Python | Make sure virtualenv is installed
  pip: name=virtualenv
